<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>§ Chapter2 Simple Statistics Test | A Mini Book of Biostatistician</title>
  <meta name="description" content="minimal handbook of Charlotte" />
  <meta name="generator" content="bookdown 0.29.3 and GitBook 2.6.7" />

  <meta property="og:title" content="§ Chapter2 Simple Statistics Test | A Mini Book of Biostatistician" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="minimal handbook of Charlotte" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="§ Chapter2 Simple Statistics Test | A Mini Book of Biostatistician" />
  
  <meta name="twitter:description" content="minimal handbook of Charlotte" />
  

<meta name="author" content="Charlotte" />


<meta name="date" content="2023-10-06" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="data-decription-inference.html"/>
<link rel="next" href="anova-analysis-of-variance.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet" />
<script src="libs/bsTable-3.3.7/bootstrapTable.js"></script>
<script src="libs/htmlwidgets-1.5.4/htmlwidgets.js"></script>
<link href="libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet" />
<script src="libs/datatables-binding-0.29/datatables.js"></script>
<link href="libs/dt-core-1.13.4/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="libs/dt-core-1.13.4/css/jquery.dataTables.extra.css" rel="stylesheet" />
<script src="libs/dt-core-1.13.4/js/jquery.dataTables.min.js"></script>
<link href="libs/dt-ext-fixedcolumns-1.13.4/css/fixedColumns.dataTables.min.css" rel="stylesheet" />
<script src="libs/dt-ext-fixedcolumns-1.13.4/js/dataTables.fixedColumns.min.js"></script>
<link href="libs/dt-ext-fixedheader-1.13.4/css/fixedHeader.dataTables.min.css" rel="stylesheet" />
<script src="libs/dt-ext-fixedheader-1.13.4/js/dataTables.fixedHeader.min.js"></script>
<link href="libs/crosstalk-1.2.0/css/crosstalk.min.css" rel="stylesheet" />
<script src="libs/crosstalk-1.2.0/js/crosstalk.min.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Mini HandBook </a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Overview</a></li>
<li class="chapter" data-level="1" data-path="data-decription-inference.html"><a href="data-decription-inference.html"><i class="fa fa-check"></i><b>1</b> Data Decription &amp; Inference</a>
<ul>
<li class="chapter" data-level="1.1" data-path="data-decription-inference.html"><a href="data-decription-inference.html#some-concepts"><i class="fa fa-check"></i><b>1.1</b> Some Concepts</a></li>
<li class="chapter" data-level="1.2" data-path="data-decription-inference.html"><a href="data-decription-inference.html#data-tables"><i class="fa fa-check"></i><b>1.2</b> Data Tables</a></li>
<li class="chapter" data-level="1.3" data-path="data-decription-inference.html"><a href="data-decription-inference.html#data-graphs"><i class="fa fa-check"></i><b>1.3</b> Data Graphs</a></li>
<li class="chapter" data-level="1.4" data-path="data-decription-inference.html"><a href="data-decription-inference.html#skewness-kurtosis"><i class="fa fa-check"></i><b>1.4</b> Skewness &amp; Kurtosis</a></li>
<li class="chapter" data-level="1.5" data-path="data-decription-inference.html"><a href="data-decription-inference.html#correlation"><i class="fa fa-check"></i><b>1.5</b> Correlation</a>
<ul>
<li class="chapter" data-level="1.5.1" data-path="data-decription-inference.html"><a href="data-decription-inference.html#pearsons-r-correlation"><i class="fa fa-check"></i><b>1.5.1</b> Pearson’s r Correlation</a></li>
<li class="chapter" data-level="1.5.2" data-path="data-decription-inference.html"><a href="data-decription-inference.html#spearmans-rho"><i class="fa fa-check"></i><b>1.5.2</b> Spearman’s Rho</a></li>
<li class="chapter" data-level="1.5.3" data-path="data-decription-inference.html"><a href="data-decription-inference.html#kendals-tau"><i class="fa fa-check"></i><b>1.5.3</b> Kendal’s Tau</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="simple-statistics-test.html"><a href="simple-statistics-test.html"><i class="fa fa-check"></i><b>2</b> Simple Statistics Test</a>
<ul>
<li class="chapter" data-level="2.1" data-path="simple-statistics-test.html"><a href="simple-statistics-test.html#normality-test"><i class="fa fa-check"></i><b>2.1</b> Normality Test</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="simple-statistics-test.html"><a href="simple-statistics-test.html#shapiro-wilk-test"><i class="fa fa-check"></i><b>2.1.1</b> Shapiro-Wilk Test</a></li>
<li class="chapter" data-level="2.1.2" data-path="simple-statistics-test.html"><a href="simple-statistics-test.html#kolmogorov-smirnov-test"><i class="fa fa-check"></i><b>2.1.2</b> Kolmogorov-Smirnov Test</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="simple-statistics-test.html"><a href="simple-statistics-test.html#one-sample-t-test"><i class="fa fa-check"></i><b>2.2</b> One sample t-Test</a></li>
<li class="chapter" data-level="2.3" data-path="simple-statistics-test.html"><a href="simple-statistics-test.html#paired-t-test"><i class="fa fa-check"></i><b>2.3</b> Paired t-Test</a></li>
<li class="chapter" data-level="2.4" data-path="simple-statistics-test.html"><a href="simple-statistics-test.html#two-samples-t-test"><i class="fa fa-check"></i><b>2.4</b> Two samples t-Test</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="simple-statistics-test.html"><a href="simple-statistics-test.html#welchs-two-sample-t-test"><i class="fa fa-check"></i><b>2.4.1</b> Welch’s two sample t-test</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="simple-statistics-test.html"><a href="simple-statistics-test.html#one-proportion-z-test"><i class="fa fa-check"></i><b>2.5</b> One Proportion Z-Test</a></li>
<li class="chapter" data-level="2.6" data-path="simple-statistics-test.html"><a href="simple-statistics-test.html#two-proportion-z-test"><i class="fa fa-check"></i><b>2.6</b> Two Proportion Z-Test</a></li>
<li class="chapter" data-level="2.7" data-path="simple-statistics-test.html"><a href="simple-statistics-test.html#one-sample-variance-test"><i class="fa fa-check"></i><b>2.7</b> One sample Variance Test</a></li>
<li class="chapter" data-level="2.8" data-path="simple-statistics-test.html"><a href="simple-statistics-test.html#two-sample-variance-test"><i class="fa fa-check"></i><b>2.8</b> Two sample Variance Test</a></li>
<li class="chapter" data-level="2.9" data-path="simple-statistics-test.html"><a href="simple-statistics-test.html#bartleets-test-levenes-test"><i class="fa fa-check"></i><b>2.9</b> Bartleet’s Test &amp; Levene’s Test</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="anova-analysis-of-variance.html"><a href="anova-analysis-of-variance.html"><i class="fa fa-check"></i><b>3</b> ANOVA (Analysis of Variance)</a>
<ul>
<li class="chapter" data-level="3.1" data-path="anova-analysis-of-variance.html"><a href="anova-analysis-of-variance.html#one-way-anova"><i class="fa fa-check"></i><b>3.1</b> One-Way ANOVA</a></li>
<li class="chapter" data-level="3.2" data-path="anova-analysis-of-variance.html"><a href="anova-analysis-of-variance.html#one-way-repeated-msearures-anova"><i class="fa fa-check"></i><b>3.2</b> One-Way Repeated Msearures ANOVA</a></li>
<li class="chapter" data-level="3.3" data-path="anova-analysis-of-variance.html"><a href="anova-analysis-of-variance.html#two-way-anova-with-interaction"><i class="fa fa-check"></i><b>3.3</b> Two-Way ANOVA (with Interaction)</a></li>
<li class="chapter" data-level="3.4" data-path="anova-analysis-of-variance.html"><a href="anova-analysis-of-variance.html#two-way-repeated-msearures-anova"><i class="fa fa-check"></i><b>3.4</b> Two-Way Repeated Msearures ANOVA</a></li>
<li class="chapter" data-level="3.5" data-path="anova-analysis-of-variance.html"><a href="anova-analysis-of-variance.html#factorial-anova"><i class="fa fa-check"></i><b>3.5</b> Factorial ANOVA</a></li>
<li class="chapter" data-level="3.6" data-path="anova-analysis-of-variance.html"><a href="anova-analysis-of-variance.html#mixed-design-anova"><i class="fa fa-check"></i><b>3.6</b> Mixed Design ANOVA</a></li>
<li class="chapter" data-level="3.7" data-path="anova-analysis-of-variance.html"><a href="anova-analysis-of-variance.html#manova"><i class="fa fa-check"></i><b>3.7</b> MANOVA</a></li>
<li class="chapter" data-level="3.8" data-path="anova-analysis-of-variance.html"><a href="anova-analysis-of-variance.html#ancova"><i class="fa fa-check"></i><b>3.8</b> ANCOVA</a></li>
<li class="chapter" data-level="3.9" data-path="anova-analysis-of-variance.html"><a href="anova-analysis-of-variance.html#multiple-comparisons"><i class="fa fa-check"></i><b>3.9</b> Multiple Comparisons</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="regression.html"><a href="regression.html"><i class="fa fa-check"></i><b>4</b> Regression</a>
<ul>
<li class="chapter" data-level="4.1" data-path="regression.html"><a href="regression.html#simple-linear-regression"><i class="fa fa-check"></i><b>4.1</b> Simple Linear Regression</a></li>
<li class="chapter" data-level="4.2" data-path="regression.html"><a href="regression.html#multiple-linear-regression"><i class="fa fa-check"></i><b>4.2</b> Multiple Linear Regression</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="regression.html"><a href="regression.html#interactions-in-multiple-linear-regression"><i class="fa fa-check"></i><b>4.2.1</b> Interactions in Multiple Linear Regression</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="regression.html"><a href="regression.html#multivariable-linear-regression"><i class="fa fa-check"></i><b>4.3</b> Multivariable Linear Regression</a></li>
<li class="chapter" data-level="4.4" data-path="regression.html"><a href="regression.html#logistic-regression"><i class="fa fa-check"></i><b>4.4</b> Logistic Regression</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="regression.html"><a href="regression.html#binomial-logistic-regression"><i class="fa fa-check"></i><b>4.4.1</b> Binomial Logistic Regression</a></li>
<li class="chapter" data-level="4.4.2" data-path="regression.html"><a href="regression.html#multinomial-logistic-regression"><i class="fa fa-check"></i><b>4.4.2</b> Multinomial Logistic Regression</a></li>
<li class="chapter" data-level="4.4.3" data-path="regression.html"><a href="regression.html#ordinal-logistic-regression"><i class="fa fa-check"></i><b>4.4.3</b> Ordinal Logistic Regression</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="regression.html"><a href="regression.html#generalized-linear-model"><i class="fa fa-check"></i><b>4.5</b> Generalized Linear Model</a></li>
<li class="chapter" data-level="4.6" data-path="regression.html"><a href="regression.html#linear-mixed-model"><i class="fa fa-check"></i><b>4.6</b> Linear Mixed Model</a></li>
<li class="chapter" data-level="4.7" data-path="regression.html"><a href="regression.html#generalized-estimating-equations-gee"><i class="fa fa-check"></i><b>4.7</b> Generalized Estimating Equations (GEE)</a></li>
<li class="chapter" data-level="4.8" data-path="regression.html"><a href="regression.html#glm-gee-concept"><i class="fa fa-check"></i><b>4.8</b> GLM &amp; GEE Concept</a></li>
<li class="chapter" data-level="4.9" data-path="regression.html"><a href="regression.html#model-performance-adj-r-square-aic-bic"><i class="fa fa-check"></i><b>4.9</b> Model performance: Adj R-square, AIC, BIC</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="categorical.html"><a href="categorical.html"><i class="fa fa-check"></i><b>5</b> Categorical</a>
<ul>
<li class="chapter" data-level="5.1" data-path="categorical.html"><a href="categorical.html#chi-square-test"><i class="fa fa-check"></i><b>5.1</b> Chi-Square Test</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="categorical.html"><a href="categorical.html#cross-table"><i class="fa fa-check"></i><b>5.1.1</b> Cross Table</a></li>
<li class="chapter" data-level="5.1.2" data-path="categorical.html"><a href="categorical.html#test-of-goodness-of-fit"><i class="fa fa-check"></i><b>5.1.2</b> Test of Goodness of Fit</a></li>
<li class="chapter" data-level="5.1.3" data-path="categorical.html"><a href="categorical.html#test-of-homogeneity"><i class="fa fa-check"></i><b>5.1.3</b> Test of Homogeneity</a></li>
<li class="chapter" data-level="5.1.4" data-path="categorical.html"><a href="categorical.html#test-of-independence"><i class="fa fa-check"></i><b>5.1.4</b> Test of Independence</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="categorical.html"><a href="categorical.html#fishers-exact-test"><i class="fa fa-check"></i><b>5.2</b> Fisher’s Exact Test</a></li>
<li class="chapter" data-level="5.3" data-path="categorical.html"><a href="categorical.html#mcnemars-test"><i class="fa fa-check"></i><b>5.3</b> McNemar’s Test</a></li>
<li class="chapter" data-level="5.4" data-path="categorical.html"><a href="categorical.html#binomial-test"><i class="fa fa-check"></i><b>5.4</b> Binomial Test</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="non-parametric.html"><a href="non-parametric.html"><i class="fa fa-check"></i><b>6</b> Non-Parametric</a>
<ul>
<li class="chapter" data-level="6.1" data-path="non-parametric.html"><a href="non-parametric.html#mann-whitney-u-test-wilcoxon-rank-sum-test"><i class="fa fa-check"></i><b>6.1</b> Mann-Whitney U Test (Wilcoxon Rank Sum Test)</a></li>
<li class="chapter" data-level="6.2" data-path="non-parametric.html"><a href="non-parametric.html#wicoxon-signed-rank-test"><i class="fa fa-check"></i><b>6.2</b> Wicoxon Signed Rank Test</a></li>
<li class="chapter" data-level="6.3" data-path="non-parametric.html"><a href="non-parametric.html#kruskal-wallis-test"><i class="fa fa-check"></i><b>6.3</b> Kruskal Wallis Test</a></li>
<li class="chapter" data-level="6.4" data-path="non-parametric.html"><a href="non-parametric.html#friedman-test"><i class="fa fa-check"></i><b>6.4</b> Friedman Test</a></li>
<li class="chapter" data-level="6.5" data-path="non-parametric.html"><a href="non-parametric.html#kolmogorov-smirnov-test-1"><i class="fa fa-check"></i><b>6.5</b> Kolmogorov-Smirnov Test</a></li>
<li class="chapter" data-level="6.6" data-path="non-parametric.html"><a href="non-parametric.html#two-sample-kolmogorov-smirnov-test"><i class="fa fa-check"></i><b>6.6</b> Two Sample Kolmogorov-Smirnov Test</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="survival-analysis.html"><a href="survival-analysis.html"><i class="fa fa-check"></i><b>7</b> Survival Analysis</a>
<ul>
<li class="chapter" data-level="7.1" data-path="survival-analysis.html"><a href="survival-analysis.html#the-survival-hazard-function"><i class="fa fa-check"></i><b>7.1</b> The Survival &amp; Hazard Function</a></li>
<li class="chapter" data-level="7.2" data-path="survival-analysis.html"><a href="survival-analysis.html#kaplan-meier-estimate"><i class="fa fa-check"></i><b>7.2</b> Kaplan-Meier Estimate</a></li>
<li class="chapter" data-level="7.3" data-path="survival-analysis.html"><a href="survival-analysis.html#cox-proportional-hazards-model"><i class="fa fa-check"></i><b>7.3</b> Cox Proportional Hazards Model</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="clinical.html"><a href="clinical.html"><i class="fa fa-check"></i><b>8</b> Clinical</a>
<ul>
<li class="chapter" data-level="8.1" data-path="clinical.html"><a href="clinical.html#phase-i-trails"><i class="fa fa-check"></i><b>8.1</b> Phase I Trails</a></li>
<li class="chapter" data-level="8.2" data-path="clinical.html"><a href="clinical.html#phase-ii-trails"><i class="fa fa-check"></i><b>8.2</b> Phase II Trails</a></li>
<li class="chapter" data-level="8.3" data-path="clinical.html"><a href="clinical.html#phase-iii-trails"><i class="fa fa-check"></i><b>8.3</b> Phase III Trails</a></li>
<li class="chapter" data-level="8.4" data-path="clinical.html"><a href="clinical.html#randomization-methods"><i class="fa fa-check"></i><b>8.4</b> Randomization Methods</a></li>
<li class="chapter" data-level="8.5" data-path="clinical.html"><a href="clinical.html#sample-size-determination"><i class="fa fa-check"></i><b>8.5</b> Sample Size Determination</a></li>
<li class="chapter" data-level="8.6" data-path="clinical.html"><a href="clinical.html#monitoring-trial-progress"><i class="fa fa-check"></i><b>8.6</b> Monitoring Trial Progress</a></li>
<li class="chapter" data-level="8.7" data-path="clinical.html"><a href="clinical.html#baseline-assement-subgroup-analysis-recruitment-multicenter-trails"><i class="fa fa-check"></i><b>8.7</b> BaseLine Assement, Subgroup Analysis, Recruitment, Multicenter Trails</a></li>
<li class="chapter" data-level="8.8" data-path="clinical.html"><a href="clinical.html#non-inferiority-data-collection-trial-closeout-intent-to-treat"><i class="fa fa-check"></i><b>8.8</b> Non-inferiority, Data Collection, Trial Closeout, Intent-to-Treat</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="real-world-data.html"><a href="real-world-data.html"><i class="fa fa-check"></i><b>9</b> Real World Data</a>
<ul>
<li class="chapter" data-level="9.1" data-path="real-world-data.html"><a href="real-world-data.html#study-design"><i class="fa fa-check"></i><b>9.1</b> Study Design</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="reference.html"><a href="reference.html"><i class="fa fa-check"></i>Reference</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">A Mini Book of Biostatistician</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="simple-statistics-test" class="section level1 hasAnchor" number="2">
<h1><span class="header-section-number">§ Chapter2</span> Simple Statistics Test<a href="simple-statistics-test.html#simple-statistics-test" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="normality-test" class="section level2 hasAnchor" number="2.1">
<h2><span class="header-section-number">2.1</span> Normality Test<a href="simple-statistics-test.html#normality-test" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="note">
<p>There are two common normality tests: <br>
1. <strong>Shapiro-Wilk test</strong> , is preferred for small samples (n &lt; 50). <br>
2. <strong>Kolmogorov-Smirnov (KS) test</strong>, for larger samples, the KS test is recommended.</p>
<ul>
<li><strong>Hypotheses:</strong> <br>
    <span class="math inline">\(H_0\)</span>: Data follows a normal distribution. <br>
    <span class="math inline">\(H_a\)</span>: Data does not follow a normal distribution.</li>
</ul>
</div>
<div id="shapiro-wilk-test" class="section level3 hasAnchor" number="2.1.1">
<h3><span class="header-section-number">2.1.1</span> Shapiro-Wilk Test<a href="simple-statistics-test.html#shapiro-wilk-test" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<blockquote>
<p><a href="https://www.itl.nist.gov/div898/handbook/prc/section2/prc213.htm">The Shapiro-Wilk Test For Normality</a></p>
</blockquote>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="simple-statistics-test.html#cb21-1" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;ggplot2&quot;</span>)</span>
<span id="cb21-2"><a href="simple-statistics-test.html#cb21-2" tabindex="-1"></a></span>
<span id="cb21-3"><a href="simple-statistics-test.html#cb21-3" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">data.frame</span>(iris<span class="sc">$</span>Sepal.Length), <span class="fu">aes</span>(<span class="at">sample=</span>iris<span class="sc">$</span>Sepal.Length)) <span class="sc">+</span> </span>
<span id="cb21-4"><a href="simple-statistics-test.html#cb21-4" tabindex="-1"></a>  <span class="fu">stat_qq</span>() <span class="sc">+</span> <span class="fu">stat_qq_line</span>(<span class="at">color=</span><span class="st">&quot;lightblue&quot;</span>) </span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-15"></span>
<img src="bookdown-demo_files/figure-html/unnamed-chunk-15-1.png" alt="Sepal.Length QQ plot" width="50%" />
<p class="caption">
Figure 2.1: Sepal.Length QQ plot
</p>
</div>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="simple-statistics-test.html#cb22-1" tabindex="-1"></a><span class="fu">shapiro.test</span>(iris<span class="sc">$</span>Sepal.Length)</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  iris$Sepal.Length
## W = 0.97609, p-value = 0.01018</code></pre>
<p>Shapiro-Wilk, p-value is 0.01018 &lt;0.05. <br>
So we reject the null hypothesis. The data are not from a normal population.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="simple-statistics-test.html#cb24-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">data.frame</span>(iris<span class="sc">$</span>Sepal.Width), <span class="fu">aes</span>(<span class="at">sample=</span>iris<span class="sc">$</span>Sepal.Width)) <span class="sc">+</span> </span>
<span id="cb24-2"><a href="simple-statistics-test.html#cb24-2" tabindex="-1"></a>  <span class="fu">stat_qq</span>() <span class="sc">+</span> <span class="fu">stat_qq_line</span>(<span class="at">color=</span><span class="st">&quot;lightblue&quot;</span>) </span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-16"></span>
<img src="bookdown-demo_files/figure-html/unnamed-chunk-16-1.png" alt="Sepal.Width QQ plot" width="50%" />
<p class="caption">
Figure 2.2: Sepal.Width QQ plot
</p>
</div>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="simple-statistics-test.html#cb25-1" tabindex="-1"></a><span class="fu">shapiro.test</span>(iris<span class="sc">$</span>Sepal.Width)</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  iris$Sepal.Width
## W = 0.98492, p-value = 0.1012</code></pre>
<p>Shapiro-Wilk, p-value is 0.1012 &gt;0.05.<br>
So we accept the null hypothesis. The data come from a normal population.</p>
</div>
<div id="kolmogorov-smirnov-test" class="section level3 hasAnchor" number="2.1.2">
<h3><span class="header-section-number">2.1.2</span> Kolmogorov-Smirnov Test<a href="simple-statistics-test.html#kolmogorov-smirnov-test" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<blockquote>
<p><a href="https://www.itl.nist.gov/div898/handbook/eda/section3/eda35g.htm">The Kolmogorov-Smirnov Test For Normality</a></p>
</blockquote>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="simple-statistics-test.html#cb27-1" tabindex="-1"></a><span class="co">#generate dataset of 100 values that follow a Poisson distribution with mean=5</span></span>
<span id="cb27-2"><a href="simple-statistics-test.html#cb27-2" tabindex="-1"></a>PoiData <span class="ot">&lt;-</span> <span class="fu">rpois</span>(<span class="at">n=</span><span class="dv">100</span>, <span class="at">lambda=</span><span class="dv">5</span>)</span>
<span id="cb27-3"><a href="simple-statistics-test.html#cb27-3" tabindex="-1"></a><span class="co">#perform Kolmogorov-Smirnov test</span></span>
<span id="cb27-4"><a href="simple-statistics-test.html#cb27-4" tabindex="-1"></a><span class="fu">ks.test</span>(PoiData, <span class="st">&quot;pnorm&quot;</span>)</span></code></pre></div>
<pre><code>## Warning in ks.test.default(PoiData, &quot;pnorm&quot;): ties should not be present for the Kolmogorov-Smirnov test</code></pre>
<pre><code>## 
##  Asymptotic one-sample Kolmogorov-Smirnov test
## 
## data:  PoiData
## D = 0.95725, p-value &lt; 2.2e-16
## alternative hypothesis: two-sided</code></pre>
<hr />
</div>
</div>
<div id="one-sample-t-test" class="section level2 hasAnchor" number="2.2">
<h2><span class="header-section-number">2.2</span> One sample t-Test<a href="simple-statistics-test.html#one-sample-t-test" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="note">
<p><strong>One-sample t-test</strong> is used to determine whether an unknown population mean is different from a specific value. For a valid test, we need assumptions: <br>
➊ Independent, ➋ Continuous, ➌ Normailty.</p>
<ul>
<li><strong>Hypotheses:</strong></li>
</ul>
<p><span class="math display">\[\begin{equation}  
H_0: \mu = \mu_0   \\
H_a: \mu \not= \mu_0
\end{equation}\]</span></p>
<ul>
<li><strong>Test Statistic:</strong></li>
</ul>
<p><span class="math display">\[\begin{equation}

t = \frac{\overline{x}-\mu{}_{0}}{s_{\overline{x}}}, \quad  
s_{\overline{x}} = \frac{s}{\sqrt{n}}

\end{equation}\]</span></p>
</div>
<p>☕<code>Example:</code></p>
<blockquote>
<p>Data : 【Modern Elementary Statistics (11th Edition): John E. Freund】</p>
<p>The yield of alfalfa from a random sample of six test plots in 1.4, 1.6, 0.9, 1.9, 2.2, and 1.2 tons per acre.</p>
</blockquote>
<ul>
<li>(a). Check whether these data can be looked upon as a sample from a normal population</li>
<li>(b). If so, test at the 0.05 level of significance whether this supports the contention that the average yield for this kind of alfalfa is 1.5 tons per acre.</li>
<li>Assumption: the population we are sampling has roughly the shape of a normal distribution.</li>
</ul>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="simple-statistics-test.html#cb30-1" tabindex="-1"></a>asfalfa <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">1.4</span>, <span class="fl">1.6</span>, <span class="fl">0.9</span>, <span class="fl">1.9</span>, <span class="fl">2.2</span>, <span class="fl">1.2</span> )</span>
<span id="cb30-2"><a href="simple-statistics-test.html#cb30-2" tabindex="-1"></a><span class="fu">t.test</span>(asfalfa, <span class="at">mu=</span><span class="fl">1.5</span>)</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  asfalfa
## t = 0.17303, df = 5, p-value = 0.8694
## alternative hypothesis: true mean is not equal to 1.5
## 95 percent confidence interval:
##  1.038130 2.028536
## sample estimates:
## mean of x 
##  1.533333</code></pre>
<ol style="list-style-type: decimal">
<li><span class="math inline">\(H_0: \mu =1.5\)</span> v.s. <span class="math inline">\(H_a: \mu \not= 1.5\)</span></li>
<li><span class="math inline">\(\alpha=0.05\)</span></li>
<li>Reject the null hypothesis if <span class="math inline">\(t\le-2.571\)</span> or <span class="math inline">\(t\ge 2.571\)</span>, where <span class="math inline">\(t = \frac{\overline{X} - \mu_0}{S/\sqrt{n}}\)</span>, and <span class="math inline">\(2.571\)</span> is the value of <span class="math inline">\(t_{0.025}\)</span> for <span class="math inline">\(6-1=5\)</span> degrees of freedom.</li>
<li>Calculating the formula for <span class="math inline">\(t\)</span>, <span class="math inline">\(t = \frac{1.5333-1.5}{0.47188/\sqrt{6}}\approx 0.173\)</span></li>
<li>Since <span class="math inline">\(t=0.173\)</span> falls between <span class="math inline">\(-2.571\)</span> and <span class="math inline">\(2.571\)</span>, the <span class="math inline">\(H_0: \mu =1.5\)</span> can not be rejected;<br />
in other word, the data tend to support the contention that the average yield of the
given kind of alfalfa is 1.5 tons per acre.</li>
</ol>
</div>
<div id="paired-t-test" class="section level2 hasAnchor" number="2.3">
<h2><span class="header-section-number">2.3</span> Paired t-Test<a href="simple-statistics-test.html#paired-t-test" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="note">
<p><strong>Paired t-test</strong> compare the means for two (and only two) related (paired) units on a continuous outcome that is normally distributed. Also know as Dependent t Test, Repeated Measures t Test.</p>
<ul>
<li><p>Data need from Normal distribution, if data from highly skewed Non-normal distributions, we use Wilcoxon signed rank Test instead.</p></li>
<li><p><strong>Hypotheses:</strong></p></li>
</ul>
<p><span class="math display">\[\begin{equation}  
H_0: \mu_1 = \mu_2   \\
H_a: \mu_1 \not= \mu_2 \\

or \\
H_0: \mu_1 - \mu_2 = 0   \\
H_a: \mu_1 - \mu_2 \not= 0 \\

\end{equation}\]</span></p>
<ul>
<li><strong>Test Statistic:</strong></li>
</ul>
<p><span class="math display">\[\begin{equation}
t = \frac{\overline{x}_{\mathrm{diff}}-0}{s_{\overline{x}}}, \quad
s_{\overline{x}} = \frac{s_{\mathrm{diff}}}{\sqrt{n}}

\end{equation}\]</span></p>
</div>
<p>☕<code>Example:</code></p>
<blockquote>
<p>Data : 【Modern Elementary Statistics (11th Edition): John E. Freund】</p>
<p>Following are the average weekly losses of worker hours due to accidents in ten industrial plants before and after the installation of an elaborate safety program:<br />
45 and 36 、 73 and 60 、 46 and 44 、 124 and 119 、 33 and 35 、<br />
57 and 51 、 83 and 77 、 34 and 29 、 26 and 24 、17 and 11</p>
<p>Use the 0.05 level of significance to test whether the safety program is effective.</p>
</blockquote>
<ul>
<li>Assumption: the population we are sampling has roughly the shape of a normal distribution.</li>
</ul>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="simple-statistics-test.html#cb32-1" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">45</span>, <span class="dv">73</span>, <span class="dv">46</span>, <span class="dv">124</span>, <span class="dv">33</span>, <span class="dv">57</span>, <span class="dv">83</span>, <span class="dv">34</span>, <span class="dv">26</span>, <span class="dv">17</span>)</span>
<span id="cb32-2"><a href="simple-statistics-test.html#cb32-2" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">36</span>, <span class="dv">60</span>, <span class="dv">44</span>, <span class="dv">119</span>, <span class="dv">35</span>, <span class="dv">51</span>, <span class="dv">77</span>, <span class="dv">29</span>, <span class="dv">24</span>, <span class="dv">11</span>)</span>
<span id="cb32-3"><a href="simple-statistics-test.html#cb32-3" tabindex="-1"></a></span>
<span id="cb32-4"><a href="simple-statistics-test.html#cb32-4" tabindex="-1"></a><span class="fu">t.test</span>(x, y, <span class="at">paired=</span><span class="cn">TRUE</span>, <span class="at">alternative=</span><span class="st">&#39;greater&#39;</span> )</span></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  x and y
## t = 4.0333, df = 9, p-value = 0.001479
## alternative hypothesis: true mean difference is greater than 0
## 95 percent confidence interval:
##  2.836619      Inf
## sample estimates:
## mean difference 
##             5.2</code></pre>
<p>The differences between the respective pairs are 9, 13, 2, 5, -2, 6, 6, 5, 2, and 6.</p>
<ol style="list-style-type: decimal">
<li><span class="math inline">\(H_0: \mu_1-\mu_2 =0\)</span> v.s. <span class="math inline">\(H_a: \mu_1-\mu_2 &gt; 0\)</span></li>
<li><span class="math inline">\(\alpha=0.05\)</span></li>
<li>Reject the null hypothesis if <span class="math inline">\(t\ge 1.833\)</span>, where <span class="math inline">\(t = \frac{\overline{X} - \mu_0}{S/\sqrt{n}}\)</span>, and <span class="math inline">\(1.8333\)</span> is the value of <span class="math inline">\(t_{0.05}\)</span> for <span class="math inline">\(10-1=9\)</span> degrees of freedom.</li>
<li>Calculating the formula for <span class="math inline">\(t\)</span>, <span class="math inline">\(t = \frac{5.2-0}{4.077/\sqrt{10}}\approx 4.033\)</span></li>
<li>Since <span class="math inline">\(t=4.033\)</span> falls exceeds <span class="math inline">\(1.833\)</span>, the <span class="math inline">\(H_0: \mu =0\)</span> must be rejected; in other word, we have shown that the industrial safety program is effective.</li>
</ol>
</div>
<div id="two-samples-t-test" class="section level2 hasAnchor" number="2.4">
<h2><span class="header-section-number">2.4</span> Two samples t-Test<a href="simple-statistics-test.html#two-samples-t-test" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="note">
<p><strong>Two samples t-test</strong> compares the means of two independent groups. Also know as Independent t Test, Unpaired t Test.</p>
<ul>
<li><p>Data need from Normal distribution, if data from highly skewed Non-normal distributions, we use Mann-Whitney U Test instead.</p></li>
<li><p>Data need Homogeneity of variances, when <a href="simple-statistics-test.html#two-sample-variance">population variances are not equal</a>, we use <a href="simple-statistics-test.html#welchs-two-sample-t-test">Welch’s t-test</a> instead.</p></li>
<li><p><strong>Hypotheses:</strong></p></li>
</ul>
<p><span class="math display">\[\begin{equation}  
H_0: \mu_1 = \mu_2   \\
H_a: \mu_1 \not= \mu_2 \\

\end{equation}\]</span></p>
<ul>
<li><strong>Test Statistic:</strong></li>
</ul>
<p><span class="math display">\[\begin{equation}  

T = \frac{\bar{Y_{1}} - \bar{Y_{2}}}
            {\sqrt{{s^{2}_{1}}/N_{1} + {s^{2}_{2}}/N_{2}}}
\end{equation}\]</span></p>
<p>          If equal variances are assumed, formula reduces to:</p>
<p><span class="math display">\[\begin{equation}  
T = \frac{\bar{Y_{1}} - \bar{Y_{2}}} {s_{p}\sqrt{1/N_{1} + 1/N_{2}}}, \quad  
s_{p}^{2} = \frac{(N_{1}-1){s^{2}_{1}} + (N_{2}-1){s^{2}_{2}}} {N_{1} + N_{2} - 2}

\end{equation}\]</span></p>
</div>
<p>☕<code>Example:</code></p>
<blockquote>
<p>Data : 【Modern Elementary Statistics (11th Edition): John E. Freund】</p>
<p>The following random samples are measurements of the heat-producing capacity ( in millions of calories pet ton ) of coal from two mines :
Mine1: 8380 8180 8500 7840 7990
Mine2: 7660 7510 7910 8070 7790</p>
<p>Use the 0.05 level of significance to test whether the difference between the means of these two samples is significant.</p>
</blockquote>
<ul>
<li>Assumption:
<ul>
<li>The population we are sampling has roughly the shape of a normal distribution. <br></li>
<li>The two samples have equal standard deviations.<br></li>
<li>The two samples are independent <br></li>
</ul></li>
</ul>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="simple-statistics-test.html#cb34-1" tabindex="-1"></a>M1 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">8380</span>, <span class="dv">8180</span>, <span class="dv">8500</span>, <span class="dv">7840</span>, <span class="dv">7990</span>)</span>
<span id="cb34-2"><a href="simple-statistics-test.html#cb34-2" tabindex="-1"></a>M2 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">7660</span>, <span class="dv">7510</span>, <span class="dv">7910</span>, <span class="dv">8070</span>, <span class="dv">7790</span>)</span>
<span id="cb34-3"><a href="simple-statistics-test.html#cb34-3" tabindex="-1"></a><span class="fu">t.test</span>(M1, M2, <span class="at">var.equal=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  M1 and M2
## t = 2.5118, df = 8, p-value = 0.03627
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##   31.95248 748.04752
## sample estimates:
## mean of x mean of y 
##      8178      7788</code></pre>
<p>We suspect the assumption of <span class="math inline">\(\sigma_1^2=\sigma_2^2\)</span></p>
<ol style="list-style-type: decimal">
<li><span class="math inline">\(H_0: \mu_1 =\mu_2\)</span> v.s. <span class="math inline">\(H_a: \mu_1 \neq \mu_2\)</span></li>
<li><span class="math inline">\(\alpha=0.05\)</span></li>
<li>Reject the null hypothesis if <span class="math inline">\(t\le-2.306\)</span> or <span class="math inline">\(t\ge2.306\)</span> , where <span class="math inline">\(t\)</span> is given by the formula above, and <span class="math inline">\(2.306\)</span> is the critical value .</li>
<li>Calculating the formula for <span class="math inline">\(t\)</span>, <span class="math inline">\(t=\frac{(8178-7788)}{245.5\sqrt{\frac{1}{5}+\frac{1}{5}}}\approx 2.51\)</span></li>
<li>Since <span class="math inline">\(t = 2.51\)</span> falls exceeds <span class="math inline">\(2.306\)</span>, the <span class="math inline">\(H_0: \mu_1 =\mu_2\)</span> must be rejected; in other words, we conclude that the difference between the two sample means is significant.</li>
</ol>
<div id="welchs-two-sample-t-test" class="section level3 hasAnchor" number="2.4.1">
<h3><span class="header-section-number">2.4.1</span> Welch’s two sample t-test<a href="simple-statistics-test.html#welchs-two-sample-t-test" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>☕<code>Example of Welch’s Two Sample t-test:</code></p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="simple-statistics-test.html#cb36-1" tabindex="-1"></a>x1 <span class="ot">=</span> <span class="fu">rnorm</span>(<span class="dv">10</span>)</span>
<span id="cb36-2"><a href="simple-statistics-test.html#cb36-2" tabindex="-1"></a>x2 <span class="ot">=</span> <span class="fu">rnorm</span>(<span class="dv">10</span>)</span>
<span id="cb36-3"><a href="simple-statistics-test.html#cb36-3" tabindex="-1"></a><span class="fu">t.test</span>(x1, x2)</span></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  x1 and x2
## t = 1.7469, df = 12.037, p-value = 0.1061
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -0.1095821  0.9975657
## sample estimates:
##   mean of x   mean of y 
## -0.09917552 -0.54316734</code></pre>
<hr />
</div>
</div>
<div id="one-proportion-z-test" class="section level2 hasAnchor" number="2.5">
<h2><span class="header-section-number">2.5</span> One Proportion Z-Test<a href="simple-statistics-test.html#one-proportion-z-test" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="note">
<ul>
<li><strong>Hypotheses:</strong></li>
</ul>
<p><span class="math display">\[\begin{equation}  
H_0: p = p_0   \\
H_a: p \not= p_0

\end{equation}\]</span></p>
<ul>
<li><strong>Test Statistic:</strong></li>
</ul>
<p><span class="math display">\[\begin{equation}  
z^*=\dfrac{\hat{p}-p_0}{\sqrt{\dfrac{p_0(1-p_0)}{n}}}
\end{equation}\]</span></p>
</div>
<p>☕<code>Example:</code></p>
<blockquote>
<p>Suppose that current vitamin pills cure 80% of all cases. A new vitamin pill has been discovered or made. In a sample of 150 patients with the lack of vitamins that were treated with the new vitamins, 95 were cured. Do the results of this study support the claim that the new vitamins have a higher cure rate than the existing vitamins?</p>
</blockquote>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="simple-statistics-test.html#cb38-1" tabindex="-1"></a><span class="fu">prop.test</span>(<span class="at">x =</span> <span class="dv">95</span>, <span class="at">n =</span> <span class="dv">160</span>, <span class="at">p =</span> <span class="fl">0.8</span>,  <span class="at">correct =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## 
##  1-sample proportions test without continuity correction
## 
## data:  95 out of 160, null probability 0.8
## X-squared = 42.539, df = 1, p-value = 6.928e-11
## alternative hypothesis: true p is not equal to 0.8
## 95 percent confidence interval:
##  0.5163169 0.6667870
## sample estimates:
##       p 
## 0.59375</code></pre>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="simple-statistics-test.html#cb40-1" tabindex="-1"></a><span class="fu">binom.test</span>(<span class="at">x =</span><span class="dv">95</span>, <span class="at">n =</span> <span class="dv">160</span>, <span class="at">p =</span> <span class="fl">0.8</span>)</span></code></pre></div>
<pre><code>## 
##  Exact binomial test
## 
## data:  95 and 160
## number of successes = 95, number of trials = 160, p-value = 2.253e-09
## alternative hypothesis: true probability of success is not equal to 0.8
## 95 percent confidence interval:
##  0.5133727 0.6705878
## sample estimates:
## probability of success 
##                0.59375</code></pre>
<p>The p-value of the test is 0.59, which is greater than the significance level alpha = 0.05. The claim that 95 out of 160 people cured with new vitamins are accurate.</p>
<div class="tip">
<p>prop.test() and binom.test() can be used to perform one-proportion test, the analysis will result in a chi-square statistic and a p-value.</p>
</div>
</div>
<div id="two-proportion-z-test" class="section level2 hasAnchor" number="2.6">
<h2><span class="header-section-number">2.6</span> Two Proportion Z-Test<a href="simple-statistics-test.html#two-proportion-z-test" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="note">
<ul>
<li><strong>Hypotheses:</strong></li>
</ul>
<p><span class="math display">\[\begin{equation}  
H_0: p_1 - p_2 = 0   \\
H_a: p_1 - p_2 \not= 0

\end{equation}\]</span></p>
<ul>
<li><strong>Test Statistic:</strong></li>
</ul>
<p><span class="math display">\[\begin{equation}  
z^*=\dfrac{(\hat{p}_1-\hat{p}_2)-0}{\sqrt{\hat{p}^*(1-\hat{p}^*)\left(\dfrac{1}{n_1}+\dfrac{1}{n_2}\right)}}, \quad

\hat{p}^*=\dfrac{x_1+x_2}{n_1+n_2}

\end{equation}\]</span></p>
</div>
<p>☕<code>Example:</code></p>
<blockquote>
<p>Let’s say we have two groups of student A and B. Group A with an early morning class of 400 students with 342 female students. Group B with a late class of 400 students with 290 female students. Use a 5% alpha level. We want to know, whether the proportions of females are the same in the two groups of the student?</p>
</blockquote>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="simple-statistics-test.html#cb42-1" tabindex="-1"></a><span class="fu">prop.test</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="dv">342</span>, <span class="dv">290</span>), <span class="at">n =</span> <span class="fu">c</span>(<span class="dv">400</span>, <span class="dv">400</span>))</span></code></pre></div>
<pre><code>## 
##  2-sample test for equality of proportions with continuity correction
## 
## data:  c(342, 290) out of c(400, 400)
## X-squared = 19.598, df = 1, p-value = 9.559e-06
## alternative hypothesis: two.sided
## 95 percent confidence interval:
##  0.07177443 0.18822557
## sample estimates:
## prop 1 prop 2 
##  0.855  0.725</code></pre>
<p>The p value of the result is 9.559e-06, greater than significance level of alpha 0.05. That means there is no difference between Two Proportions.</p>
<div class="tip">
<p>Chi-square test of independence on a 2 × 2 table, the resulting Chi-square test statistic would be equal to the square of the Z-test statistic from the Z-test of two independent proportions.</p>
</div>
<hr />
</div>
<div id="one-sample-variance-test" class="section level2 hasAnchor" number="2.7">
<h2><span class="header-section-number">2.7</span> One sample Variance Test<a href="simple-statistics-test.html#one-sample-variance-test" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="note">
<ul>
<li><strong>Hypotheses:</strong></li>
</ul>
<p><span class="math display">\[\begin{equation}  
H_0: \sigma^2=\sigma^2_0 \\
H_a: \sigma^2 \not= \sigma^2_0
\end{equation}\]</span></p>
<ul>
<li><strong>Test Statistic:</strong></li>
</ul>
<p><span class="math display">\[\begin{equation}

\chi^2=\dfrac{(n-1)S^2}{\sigma^2_0}

\end{equation}\]</span></p>
</div>
<p>☕<code>Example:</code></p>
<blockquote>
<p>Generate 20 observations from a normal distribution with parameters mean=2 and sd=1. Test the null hypothesis that the true variance is equal to 0.5 against the alternative that the true variance is not equal to 0.5.</p>
</blockquote>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="simple-statistics-test.html#cb44-1" tabindex="-1"></a><span class="fu">library</span>(EnvStats)</span></code></pre></div>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="simple-statistics-test.html#cb45-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">23</span>) </span>
<span id="cb45-2"><a href="simple-statistics-test.html#cb45-2" tabindex="-1"></a>vardata <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">20</span>, <span class="at">mean =</span> <span class="dv">2</span>, <span class="at">sd =</span> <span class="dv">1</span>) </span>
<span id="cb45-3"><a href="simple-statistics-test.html#cb45-3" tabindex="-1"></a><span class="fu">varTest</span>(vardata, <span class="at">sigma.squared =</span> <span class="fl">0.5</span>) </span></code></pre></div>
<pre><code>## $statistic
## Chi-Squared 
##     28.6409 
## 
## $parameters
## df 
## 19 
## 
## $p.value
## [1] 0.1436947
## 
## $estimate
## variance 
## 0.753708 
## 
## $null.value
## variance 
##      0.5 
## 
## $alternative
## [1] &quot;two.sided&quot;
## 
## $method
## [1] &quot;Chi-Squared Test on Variance&quot;
## 
## $data.name
## [1] &quot;vardata&quot;
## 
## $conf.int
##       LCL       UCL 
## 0.4359037 1.6078623 
## attr(,&quot;conf.level&quot;)
## [1] 0.95
## 
## attr(,&quot;class&quot;)
## [1] &quot;htestEnvStats&quot;</code></pre>
</div>
<div id="two-sample-variance-test" class="section level2 hasAnchor" number="2.8">
<h2><span class="header-section-number">2.8</span> Two sample Variance Test<a href="simple-statistics-test.html#two-sample-variance-test" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="note">
<ul>
<li><strong>Hypotheses:</strong></li>
</ul>
<p><span class="math display">\[\begin{equation}  
H_0: \sigma^2_1=\sigma^2_2 \\
H_a: \sigma^2_1 \not= \sigma^2_2
\end{equation}\]</span></p>
<ul>
<li><strong>Test Statistic:</strong></li>
</ul>
<p><span class="math display">\[\begin{equation}

F=\dfrac{S^2_1}{S^2_2} \quad \sim \quad   F_{1-(\alpha/2)}(n-1,m-1)=\dfrac{1}{F_{\alpha/2}(m-1,n-1)}

\end{equation}\]</span></p>
</div>
<p>☕<code>Example:</code></p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="simple-statistics-test.html#cb47-1" tabindex="-1"></a>data1 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">50</span>, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">2</span>)</span>
<span id="cb47-2"><a href="simple-statistics-test.html#cb47-2" tabindex="-1"></a>data2 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">30</span>, <span class="at">mean =</span> <span class="dv">1</span>, <span class="at">sd =</span> <span class="dv">1</span>)</span>
<span id="cb47-3"><a href="simple-statistics-test.html#cb47-3" tabindex="-1"></a><span class="fu">var.test</span>(data1, data2)      <span class="co"># Do data1 and data2 have the same variance?</span></span></code></pre></div>
<pre><code>## 
##  F test to compare two variances
## 
## data:  data1 and data2
## F = 3.4928, num df = 49, denom df = 29, p-value = 0.0005706
## alternative hypothesis: true ratio of variances is not equal to 1
## 95 percent confidence interval:
##  1.754874 6.571449
## sample estimates:
## ratio of variances 
##            3.49282</code></pre>
<p><br></p>
<p><img src="img/TestVariance.png" width="48%" style="display: block; margin: auto;" /></p>
</div>
<div id="bartleets-test-levenes-test" class="section level2 hasAnchor" number="2.9">
<h2><span class="header-section-number">2.9</span> Bartleet’s Test &amp; Levene’s Test<a href="simple-statistics-test.html#bartleets-test-levenes-test" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="note">
<p>Test if k samples have equal variances. Equal variances across samples is called homogeneity of variances. <br>
1. <strong>Bartleet’s test</strong>, samples come from Normal distribution. <br>
2. <strong>Levene’s test</strong>, samples come from Non-Normal distribution.</p>
<ul>
<li><strong>Hypotheses: </strong> <br></li>
</ul>
<p><span class="math display">\[\begin{align}

&amp; H_0: \sigma^2_1 = \sigma^2_2 = ... = \sigma^2_k    \\
&amp; H_a: \sigma^2_i \not = \sigma^2_j ~ for ~ at ~ least ~ one ~ pair (i,j).

\end{align}\]</span></p>
</div>
<p><br></p>
<blockquote>
<p><a href="https://www.itl.nist.gov/div898/handbook/eda/section3/eda357.htm">Bartlett’s Test</a></p>
</blockquote>
<p>☕<code>Example:</code></p>
<blockquote>
<p>Example in R is performed using the Oranges dataset. Here, we wish to test if the variances circumference of each tree. The null hypothesis states that the trees will have the same variances, otherwise for the alternative hypothesis.</p>
</blockquote>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="simple-statistics-test.html#cb49-1" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;datasets&quot;</span>)</span>
<span id="cb49-2"><a href="simple-statistics-test.html#cb49-2" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;ggplot2&quot;</span>)</span>
<span id="cb49-3"><a href="simple-statistics-test.html#cb49-3" tabindex="-1"></a></span>
<span id="cb49-4"><a href="simple-statistics-test.html#cb49-4" tabindex="-1"></a>Orangedata <span class="ot">&lt;-</span> Orange</span>
<span id="cb49-5"><a href="simple-statistics-test.html#cb49-5" tabindex="-1"></a></span>
<span id="cb49-6"><a href="simple-statistics-test.html#cb49-6" tabindex="-1"></a><span class="fu">ggplot</span>(Orangedata, <span class="fu">aes</span>(Tree, circumference, <span class="at">color=</span>Tree) )<span class="sc">+</span> <span class="fu">geom_boxplot</span>()<span class="sc">+</span> <span class="fu">scale_color_brewer</span>(<span class="at">palette=</span><span class="st">&quot;Blues&quot;</span>)</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-28-1.png" width="50%" /></p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="simple-statistics-test.html#cb50-1" tabindex="-1"></a><span class="fu">bartlett.test</span>(circumference <span class="sc">~</span> Tree, <span class="at">data =</span> Orangedata)</span></code></pre></div>
<pre><code>## 
##  Bartlett test of homogeneity of variances
## 
## data:  circumference by Tree
## Bartlett&#39;s K-squared = 2.4607, df = 4, p-value = 0.6517</code></pre>
<p>p-value of 0.6517 is not less than the significance level of 0.05. This means the null hypothesis can not be rejected that the variance is the same for all treatment groups. This concludes that there is no proof to recommend that the variance in circumference is different for the tree groups.</p>
<p><br></p>
<blockquote>
<p><a href="https://www.itl.nist.gov/div898/handbook/eda/section3/eda35a.htm">Levene’s Test</a></p>
</blockquote>
<p>☕<code>Example:</code></p>
<blockquote>
<p>Consider the R’s inbuilt PlantGrowth dataset that gives the dried weight of three groups of ten batches of plants, wherever every group of ten batches got a different treatment. The weight variable gives the weight of the batch and the group variable gives the treatment received either ctrl, trt1 or trt2.</p>
</blockquote>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="simple-statistics-test.html#cb52-1" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;car&quot;</span>)</span></code></pre></div>
<pre><code>## Loading required package: carData</code></pre>
<pre><code>## 
## Attaching package: &#39;car&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:EnvStats&#39;:
## 
##     qqPlot</code></pre>
<pre><code>## The following object is masked from &#39;package:purrr&#39;:
## 
##     some</code></pre>
<pre><code>## The following object is masked from &#39;package:dplyr&#39;:
## 
##     recode</code></pre>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="simple-statistics-test.html#cb58-1" tabindex="-1"></a><span class="fu">ggplot</span>(PlantGrowth, <span class="fu">aes</span>(group, weight, <span class="at">color=</span>group) )<span class="sc">+</span> </span>
<span id="cb58-2"><a href="simple-statistics-test.html#cb58-2" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()<span class="sc">+</span> <span class="fu">scale_color_brewer</span>(<span class="at">palette=</span><span class="st">&quot;Blues&quot;</span>)</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-29-1.png" width="60%" /></p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="simple-statistics-test.html#cb59-1" tabindex="-1"></a><span class="fu">leveneTest</span>(weight <span class="sc">~</span> group, <span class="at">data =</span> PlantGrowth)</span></code></pre></div>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = median)
##       Df F value Pr(&gt;F)
## group  2  1.1192 0.3412
##       27</code></pre>
<p>p-value of 0.3412 is not less than the significance level of 0.05. The null hypothesis can not be rejected that the variance is the same for all treatment groups.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="data-decription-inference.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="anova-analysis-of-variance.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/BioStat-2-SimpleTest.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["bookdown-demo.pdf", "bookdown-demo.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
